version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn  -s .circleci/m2settings.xml dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn  -s .circleci/m2settings.xml integration-test

  master:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn  -s .circleci/m2settings.xml dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn  -s .circleci/m2settings.xml build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.${CIRCLE_BUILD_NUM} versions:commit
      - run: mvn  -s .circleci/m2settings.xml package
      - run: mvn  -s .circleci/m2settings.xml deploy


workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - artifactory


      - master:
          context:
            - artifactory
          requires:
            - build
          filters:
            branches:
              only: master
